services:
  nodejs-server:
    image: node:latest
    command: node /temp/server.js
    volumes:
    - .:/temp/
  nodejs-client:
    image: node:latest
    command: node /temp/client.js
    volumes:
    - .:/temp/
    restart: always
    depends_on: 
    -  nodejs-server
